version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - make install
  pre_build:
    commands:
      - make lint
      - make format
  build:
    commands:
      - make test

