version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - make install
  code_quality:
    commands:
      - make lint
      - make format
  test:
    commands:
      - make test

